import type { AoriSwapWidgetConfig } from '@aori/mega-swap-widget';

export const aoriConfig: AoriSwapWidgetConfig = {
  vtApiBaseUrl: '/api/vt',
  walletConnectProjectId: '3ce48d5c2eb47bf61eef12ecad07e542',
  rpcOverrides: {
    1: '/api/rpc/1',
    10: '/api/rpc/10',
    56: '/api/rpc/56',
    8453: '/api/rpc/8453',
    42161: '/api/rpc/42161',
    9745: '/api/rpc/9745',
    143: '/api/rpc/143',
    4326: '/api/rpc/4326',
  },
  theme: {
    mode: 'dark',
    light: {
      background: '#1a1a1a',
      foreground: '#0a0a0a',
      card: '#ffffff',
      'card-foreground': '#0a0a0a',
      popover: '#f5f5f5',
      'popover-foreground': '#0a0a0a',
      primary: '#FDB913',
      'primary-foreground': '#ffffff',
      secondary: '#111010',
      'secondary-foreground': '#171717',
      muted: '#f5f5f5',
      'muted-foreground': '#737373',
      accent: '#f5f5f5',
      'accent-foreground': '#171717',
      destructive: '#e7000b',
      'destructive-foreground': '#ffffff',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#FDB913',
      radius: '0rem',
      'letter-spacing': '0em',
      'status-pending': '#a1a1aa',
      'status-received': '#f59e0b',
      'status-completed': '#10b981',
      'status-failed': '#ef4444'
    },
    dark: {
      background: '#141414',
      foreground: '#ffffff',
      card: '#141414',
      'card-foreground': '#ffffff',
      popover: '#1a1a1a',
      'popover-foreground': '#ffffff',
      primary: '#FDB913',
      'primary-foreground': '#000000',
      secondary: '#1a1a1a',
      'secondary-foreground': '#ffffff',
      muted: '#141414',
      'muted-foreground': '#6B7280',
      accent: '#1a1a1a',
      'accent-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#252525',
      input: '#0f0f0f',
      ring: '#FDB913',
      radius: '0.75rem',
      'border-style': 'solid',
      'shadow-opacity': '0',
      'font-sans': '"KHTeka", "Helvetica Neue", Helvetica, Arial, sans-serif',
      'font-mono': '"KHTekaMono", ui-monospace, monospace',
      'letter-spacing': '0.010em',
      'status-pending': '#a1a1aa',
      'status-received': '#FDB913',
      'status-completed': '#10b981',
      'status-failed': '#ef4444'
    }
  },
  tokens: {
    defaultBase: {
      chainId: 1,
      address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    },
    defaultQuote: {
      chainId: 4326,
      address: '0xFAfDdbb3FC7688494971a79cc65DCa3EF82079E7',
    },
    inputSelectionSearch: true,
    outputSelectionSearch: true,
    showInputSelectionTokenBalances: true,
    showOutputSelectionTokenBalances: false,
    lockBase: false,
    lockQuote: false,
    disableInverting: false,
    supportedOutputTokens: [
      { chainId: 4326, address: '0xFAfDdbb3FC7688494971a79cc65DCa3EF82079E7' }, // USDM MegaETH
    ],
    supportedOutputChains: [4326],
  },
  appearance: {
    widgetType: 'default',
    tokenDisplay: 'default',
    tokenBadgeOrientation: 'left',
    assetMenuVariant: 'default',
    amountInputVariant: 'default',
    hideAmountInputSymbol: false,
    quoteLoaderVariant: 'expanded',
    fillContainer: true,
    hideBorder: true,
    walletButtonEnabled: true
  },
  settings: {
    defaultSlippage: 0.01
  }
};